#!/bin/sh

# environment
echo APP_ENV=$APP_ENV
echo APP_NAME=$APP_NAME

# build
echo DISTRIB_ID=$DISTRIB_ID
echo BASE_IMAGE=$BASE_IMAGE

# System package
echo BUILD_PACKAGES=$BUILD_PACKAGES
echo DEVELOPMENT_PACKAGES=$DEVELOPMENT_PACKAGES
echo TEST_PACKAGES=$TEST_PACKAGES

# Physical
echo PROJECT_FOLDER=$PROJECT_FOLDER
echo DATA_FOLDER=$DATA_FOLDER

echo ==========
# /bin/sh
